import Link from "next/link";

import { IsoDateInput } from "@/components/forms/iso-date-input";
import type { Locale } from "@/lib/i18n/config";
import { localizeCategoryLabel, type Dictionary } from "@/lib/i18n/dictionaries";
import { activeFilterCount, type ListingFilters } from "@/lib/listings/filters";

type Taxonomy = { cities: { slug: string; name: string }[]; organizations: { slug: string; name: string }[]; categories: { slug: string; label: string; kind: string }[] };

export function ListingFiltersForm({ filters, taxonomy, count, locale, dictionary }: { filters: ListingFilters; taxonomy: Taxonomy; count: number; locale: Locale; dictionary: Dictionary }) {
  const active = activeFilterCount(filters);
  return <aside className="filters-panel"><form method="get" action="/" className="filters-form"><div className="filters-heading"><h2>{dictionary.filterTitle}</h2>{active ? <Link href="/">{dictionary.filterClearAll} ({active})</Link> : null}</div><label>{dictionary.filterCity}<select name="city" defaultValue={filters.city ?? ""}><option value="">{dictionary.filterAllCities}</option>{filters.city && !taxonomy.cities.some(({ slug }) => slug === filters.city) ? <option value={filters.city}>{filters.city}</option> : null}{taxonomy.cities.map((city) => <option key={city.slug} value={city.slug}>{city.name}</option>)}</select></label><label>{dictionary.filterOrganization}<select name="organization" defaultValue={filters.organization ?? ""}><option value="">{dictionary.filterAllOrganizations}</option>{filters.organization && !taxonomy.organizations.some(({ slug }) => slug === filters.organization) ? <option value={filters.organization}>{filters.organization}</option> : null}{taxonomy.organizations.map((organization) => <option key={organization.slug} value={organization.slug}>{organization.name}</option>)}</select></label><fieldset><legend>{dictionary.filterResourceType}</legend><label><input type="radio" name="kind" value="" defaultChecked={!filters.kind} /> {dictionary.filterEverything}</label><label><input type="radio" name="kind" value="housing" defaultChecked={filters.kind === "housing"} /> {dictionary.filterHousing}</label><label><input type="radio" name="kind" value="item" defaultChecked={filters.kind === "item"} /> {dictionary.filterItems}</label><label><input type="radio" name="kind" value="other" defaultChecked={filters.kind === "other"} /> {dictionary.filterOther}</label></fieldset><label>{dictionary.filterCategory}<select name="category" defaultValue={filters.category ?? ""}><option value="">{dictionary.filterAllCategories}</option>{filters.category && !taxonomy.categories.some(({ slug }) => slug === filters.category) ? <option value={filters.category}>{filters.category}</option> : null}{taxonomy.categories.map((category) => <option key={`${category.kind}-${category.slug}`} value={category.slug}>{localizeCategoryLabel(locale, category.slug, category.label)}</option>)}</select></label><label>{dictionary.filterMaxPrice}<input type="number" name="maxPrice" min="0" step="1" defaultValue={filters.maxPrice} placeholder={dictionary.filterAnyPrice} /></label><label>{dictionary.filterAvailableBy}<IsoDateInput name="availableBy" defaultValue={filters.availableBy} /></label><button className="button-primary">{dictionary.filterApply}</button></form><p className="result-announcement" role="status" aria-live="polite">{count} {dictionary.filterCurrent} {count === 1 ? dictionary.filterListing : dictionary.filterListings}</p></aside>;
}
